# Generated by Django 5.0.14 on 2026-07-07 06:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airline_logos/')),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('fleet_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('terminal_info', models.TextField(blank=True, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('map_embed_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cabin_class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], default='Economy', max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('baggage_allowance', models.CharField(default='15kg check-in, 7kg cabin', max_length=100)),
                ('refund_policy', models.TextField(default='Refundable with deduction fee. Cancel before 24 hours.')),
                ('meals_included', models.BooleanField(default=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('travel_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flights.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, help_text='in km', max_digits=8)),
                ('duration', models.DurationField(help_text='Expected duration of flight')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origins', to='flights.airport')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.route'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], default='Economy', max_length=20)),
                ('seat_type', models.CharField(choices=[('Window', 'Window'), ('Aisle', 'Aisle'), ('Middle', 'Middle'), ('Emergency Exit', 'Emergency Exit')], default='Middle', max_length=30)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight')),
            ],
            options={
                'unique_together': {('flight', 'seat_number')},
            },
        ),
    ]
